stages:
  build_dataset:
    cmd: jupyter nbconvert --to notebook --execute --inplace 10.11-prepare-dataset.ipynb
    deps:
    - 10.11-prepare-dataset.ipynb
    - ../data/def_frame_annot_sense_ids.txt
    outs:
    - ../data/defgen_dataset_cwn/
    - ../data/denoising_dataset_cwn/
  train_denoise_v1.0:
    cmd: jupyter nbconvert --to notebook --execute --inplace 20.10-denoise-training.ipynb
    deps:
    - 20.10-denoise-training.ipynb
    - ../data/denoising_dataset_cwn/
    outs:
    - ../data/models/vec4gloss-denoise-220628-1510/
  train_defgen_v1.0:
    cmd: jupyter nbconvert --to notebook --execute --inplace 20.20-defgen-training.ipynb
    deps:
    - 20.20-defgen-training.ipynb
    - ../data/defgen_dataset_cwn/
    outs:
    - ../data/models/vec4gloss-defgen-220628-1546/
    desc: |
      v1.0 is a defgen model based on the denoising pretrained model, and runs for 5 epochs
  train_defgen_v1.1:
    cmd: jupyter nbconvert --to notebook --execute --inplace 20.21-defgen-training-run2.ipynb
    deps:
    - 20.21-defgen-training-run2.ipynb
    - ../data/defgen_dataset_cwn/
    outs:
    - ../data/models/vec4gloss-defgen-220629-1250/
    desc: |
      v1.1 is same as v1.0, but runs for 10 epochs

  prepare_rating:
    cmd: nbconvert --execute --inplace --to notebook 30.01-prepare-rating.ipynb
    deps:
    - ../data/asbc5_words_pos.pkl
    - ../data/defgen_dataset_cwn
    - ../data/models/vec4gloss-defgen-220629-1250
    outs:
    - ../data/rating_materials.csv:
        cache: false
  prepare_rating.n10:
    cmd: nbconvert --execute --inplace --to notebook 30.01-prepare-rating.ipynb
    deps:
    - ../data/asbc5_words_pos.pkl
    - ../data/defgen_dataset_cwn
    - ../data/models/vec4gloss-defgen-220629-1250
    outs:
    - ../data/rating_materials.n10.csv:
        cache: false
    - ../data/rating_materials.n10.raw.pkl
  rating_stat:
    cmd: nbconvert --inplace --execute --to notebook 30.10-rating-data-eda-1.ipynb
    deps:
    - ../data/rating_materials.n10.csv
    - ../data/rating_raw_data_220707.csv
    - 30.10-rating-data-eda-1.ipynb
    outs:
    - ../data/rating_response_stat.csv
  build-annotframe:
    cmd: nbconvert --to notebook --execute --inplace 30.23-build-annot-frameinfo.ipynb
    deps:
    - ../data/annotation.json
    - ../data/models/vec4gloss-defgen-220629-1250
    outs:
    - ../data/annot_frameinfo_list.pkl
