stages:
  build_dataset:
    cmd: jupyter nbconvert --to notebook --execute --inplace 10.11-prepare-dataset.ipynb
    deps:
    - 10.11-prepare-dataset.ipynb
    - ../data/def_frame_annot_sense_ids.txt
    outs:
    - ../data/defgen_dataset_cwn/
    - ../data/denoising_dataset_cwn/
