stages:
  build_dataset:
    cmd: nbconvert --to notebook --inplace 10.11-prepare-dataset.ipynb
    deps:
    - ../data/def_frame_annot_sense_ids.txt
    outs:
    - ../data/defgen_dataset_cwn
    - ../data/denoising_dataset_cwn
